Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kcoreaddons' : '@same'
    'frameworks/kwallet' : '@same'
    'frameworks/kio' : '@same'
    'frameworks/knotifications' : '@same'
    'frameworks/kparts' : '@same'

Options:
  test-before-installing: True
